Repository cca-ffodregamdi/RunningHi-Back, pull requests merged in 2024-06, with the labels that each got.

#274 [Refactor- May 4th, 2024] - {TestData} PostKeyword 관련 데이터 삭제
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/domain/enumtype/Difficulty.java
  src/test/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatchTests.java
Labels: 🔨 Refactor

#280 [Refactoring - Jun 1st, 2024] - {DUMMY} 테스트용 토큰 재발급 수정
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestMemberRepository.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestToken.java
Labels: 🔨 Refactor

#286 [Chore - Jun 1st, 2024]{Deploy} 배포 CI/CD 설정
  .github/workflows/pr-build-gradle.yml
  .github/workflows/push-deploy-gradle.yml
  .gitignore
  build.gradle
Labels: 🌏 Deploy, ⚙ Setting

#291 [Feature- Jun 1st, 2024] - {DUMMY} test/data 시 전체 초기화 & insert
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestDatabaseMapper.java
  src/main/resources/data/alarms.sql
  src/main/resources/data/bookmarks.sql
  src/main/resources/data/feebacks.sql
  src/main/resources/data/members.sql
  src/main/resources/data/postreports.sql
  src/main/resources/data/posts.sql
  src/main/resources/data/replies.sql
  src/main/resources/data/replyreports.sql
  src/main/resources/mapper/ResetDatabase.xml
Labels: ✨ Feature

#294 [Fix- Jun 1st, 2024] {Dummy} 게시글 상세보기 Response 수정
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
Labels: ⚒️Fix

#300 [Refactoring - Jun 1st, 2024] - {Member} 카카오 로그인 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/request/KakaoLoginRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/service/KakaoOauthService.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#298 [Feature - Jun 2nd, 2024]{Challenge} 챌린지 CRUD, 챌린지 참여 및 기록 업데이트 기능
  src/main/java/com/runninghi/runninghibackv2/application/controller/ChallengeController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/request/CreateChallengeRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/request/UpdateChallengeRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/CreateChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/DeleteChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/GetChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/UpdateChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/request/CreateMyChallengeRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/CreateMyChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/GetMyChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ChallengeService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/MyChallengeService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Challenge.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Member.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/MemberChallenge.java
  src/main/java/com/runninghi/runninghibackv2/domain/enumtype/ChallengeCategory.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ChallengeRepository.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/MemberChallengeRepository.java
Labels: ✨ Feature

#304 [Feature- Jun 1st, 2024] - {Post, Reply} 게시글 상세조회 시 Response 수정
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetReplyListResponse.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
  src/main/resources/data/replies.sql
  src/main/resources/mapper/ResetDatabase.xml
Labels: ✨ Feature

#308 [Refactoring - Jun 1st, 2024] - {Member} 회원가입 시 response 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/CreateMemberResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/GetMemberResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AppleOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/KakaoOauthService.java
Labels: 🔨 Refactor

#313 Feature - [Member] MemberId를 반환하는 API 생성
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/GetMemberNoResponse.java
Labels: ✨ Feature

#314 [Refactor - Jun 3rd, 2024]{Dummy} 엔티티 설계
  src/main/resources/data/posts.sql
  src/main/resources/mapper/ResetDatabase.xml
Labels: 🔨 Refactor

#315 [#314] Bugfix : 2024-06-14 신고 더미데이터 오류 수정
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestDatabaseMapper.java
  src/main/resources/mapper/ResetDatabase.xml
Labels: 🐞 BugFix

#319 [Refactor - Jun 3rd, 2024] 댓글 조회 시 요청자와 댓글들의 본인 소유 여부 확인 구현
  src/main/java/com/runninghi/runninghibackv2/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/GetReplyListByMemberRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/GetReplyListRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetReplyListResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ReplyService.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/ReplyQueryRepositoryImpl.java
Labels: 🔨 Refactor

#322 [BugFix - Jun 3rd, 2024] 배포 서버 로깅 버그 이슈
  .github/workflows/push-deploy-gradle.yml
Labels: 🐞 BugFix

#324 [Refactor - Jun 3rd, 2024] post 상세 보기 시에 북마크 개수 응답
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: 🔨 Refactor

#326 [Feature- Jun 3rd, 2024] 게시글 상세보기 Response 시 본인 작성 여부 포함
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/PostQueryRepository.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/PostChecker.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: ✨ Feature

#337 [Feature - Jun 3rd, 2024]{Challenge} 챌린지 DummyData 생성 Mapper 추가
  src/main/java/com/runninghi/runninghibackv2/application/dto/postreport/response/GetPostReportResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/replyreport/response/GetReplyReportResponse.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestDatabaseMapper.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/PostReport.java
  src/main/resources/mapper/ResetDatabase.xml
  src/test/java/com/runninghi/runninghibackv2/application/service/PostReportServiceTests.java
  src/test/java/com/runninghi/runninghibackv2/application/service/ReplyReportServiceTests.java
Labels: ✨ Feature

#340 [Refactor - Jun, 2024] 댓글 수정 API 리팩토링
  src/main/java/com/runninghi/runninghibackv2/application/controller/FeedbackController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/UpdateReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ReplyService.java
  src/main/resources/mapper/ResetDatabase.xml
  src/test/java/com/runninghi/runninghibackv2/application/controller/FeedbackControllerTest.java
  src/test/java/com/runninghi/runninghibackv2/application/service/ReplyServiceTest.java
Labels: 🔨 Refactor

#344 Feature - apple 관련 ci/cd 설정 추가
  .github/workflows/push-deploy-gradle.yml
Labels: 🔨 Refactor

#345 [Refactor - Jun, 2024] 댓글 수정 날짜 -> 수정 여부 업데이트
  src/main/java/com/runninghi/runninghibackv2/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/GetReplyListByMemberRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/GetReportedReplySearchRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/UpdateReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/CreateReplyResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetReplyListResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetReportedReplyResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/UpdateReplyResponse.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/ReplyQueryRepositoryImpl.java
  src/main/resources/mapper/ResetDatabase.xml
Labels: 🔨 Refactor

#368 Feature - 챌린지 랭킹 조회, 중복참여 방지, 전체조회 API 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/ChallengeController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/ScoreController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/GetAllChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/GetChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/GetAllMyChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/GetChallengeRankingResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/GetMyChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/score/GetRankingResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ChallengeService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/MyChallengeService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ScoreService.java
  src/main/java/com/runninghi/runninghibackv2/common/schedule/ScoreCleanUpBatch.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Score.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ChallengeRepository.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/MemberChallengeRepository.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ScoreRepository.java
  src/main/resources/mapper/ResetDatabase.xml
Labels: 🔨 Refactor, ✨ Feature

#369 [Refactor - Jun, 2024] 댓글 리스트 조회 리팩토링
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/GetReplyListRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetReplyListResponse.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/ReplyQueryRepositoryImpl.java
Labels: 🔨 Refactor

#372 [#371] 도커 컨테이너를 활용한 CI/CD 배포 설정
  .github/workflows/pr-build-gradle.yml
  .github/workflows/push-deploy-gradle.yml
  Dockerfile
  src/main/java/com/runninghi/runninghibackv2/application/dto/bookmark/response/CreateBookmarkResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetReplyListResponse.java
Labels: 🌏 Deploy

#376 [Feature - Jun 3rd, 2024]{Post} 게시글 수정 변경사항 적용
  src/main/java/com/runninghi/runninghibackv2/application/controller/ImageController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/UpdatePostRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/UpdatePostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ImageService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Image.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Post.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ImageRepository.java
  src/main/resources/data/images.sql
  src/main/resources/data/postreports.sql
  src/main/resources/mapper/ResetDatabase.xml
Labels: ✨ Feature

#379 [#378] Ci : 2024-06-28 issue branch ci 설정
  .github/issue-branch.yml
  .github/workflows/make-issue-template.yml
Labels: 🏻‍🎤 Ci

#384 [#383] 댓글 페이징 제거, 정렬 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/GetReplyListRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetPostReplyResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/UpdateReplyResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ReplyReportService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ReplyService.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
  src/main/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatch.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Reply.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ReplyQueryRepository.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ReplyRepository.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/ReplyQueryRepositoryImpl.java
  src/test/java/com/runninghi/runninghibackv2/application/service/ReplyReportServiceTests.java
  src/test/java/com/runninghi/runninghibackv2/application/service/ReplyServiceTest.java
  src/test/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatchTests.java
Labels: 🔨 Refactor

#386 [#385] Bugfix : 2024-06-29 더미데이터 주입 간 외래키 관계 설정 추가
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
Labels: 🐞 BugFix

#388 [#387] Refactor : 2024-06-29 댓글 리스트 조회 응답 content 포함으로 리팩토링
  src/main/java/com/runninghi/runninghibackv2/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/GetReplyList.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetContentResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ReplyService.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ReplyQueryRepository.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/ReplyQueryRepositoryImpl.java
Labels: 🔨 Refactor, ⚒️Fix
