Repository cca-ffodregamdi/RunningHi-Back, pull requests merged in 2024-03, with the labels that each got.

#19 [Feature - March 1st, 2024]{COMMON} deleteDate 제거
  src/main/java/com/runninghi/runninghibackv2/common/entity/BaseTimeEntity.java
Labels: ⚒️Fix

#23 [Feature - March 1st, 2024]{POST, POSTKEYWORD} 엔티티 수정사항
  src/main/java/com/runninghi/runninghibackv2/adminpost/application/dto/test.java
  src/main/java/com/runninghi/runninghibackv2/adminpost/application/service/test.java
  src/main/java/com/runninghi/runninghibackv2/adminpost/domain/aggregate/entity/AdminPost.java
  src/main/java/com/runninghi/runninghibackv2/adminpost/domain/aggregate/vo/test.java
  src/main/java/com/runninghi/runninghibackv2/adminpost/domain/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/adminpost/domain/service/test.java
  src/main/java/com/runninghi/runninghibackv2/adminpost/infrastructure/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/adminpost/infrastructure/service/test.java
  src/main/java/com/runninghi/runninghibackv2/common/entity/Role.java
  src/main/java/com/runninghi/runninghibackv2/keyword/domain/aggregate/entity/Keyword.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/application/dto/test.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/application/service/test.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/aggregate/entity/PostKeyword.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/aggregate/vo/PostKeywordVO.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/service/test.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/infrastructure/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/infrastructure/service/test.java
  src/main/java/com/runninghi/runninghibackv2/member/domain/aggregate/entity/Member.java
  src/main/java/com/runninghi/runninghibackv2/member/domain/aggregate/entity/Role.java
  src/main/java/com/runninghi/runninghibackv2/memberpost/application/dto/test.java
  src/main/java/com/runninghi/runninghibackv2/memberpost/application/service/test.java
  src/main/java/com/runninghi/runninghibackv2/memberpost/domain/aggregate/entity/MemberPost.java
  src/main/java/com/runninghi/runninghibackv2/memberpost/domain/aggregate/vo/test.java
  src/main/java/com/runninghi/runninghibackv2/memberpost/domain/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/memberpost/domain/service/test.java
  src/main/java/com/runninghi/runninghibackv2/memberpost/infrastructure/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/memberpost/infrastructure/service/test.java
  src/main/java/com/runninghi/runninghibackv2/post/application/dto/test.java
  src/main/java/com/runninghi/runninghibackv2/post/application/service/test.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/aggregate/entity/Post.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/aggregate/vo/test.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/service/test.java
  src/main/java/com/runninghi/runninghibackv2/post/infrastructure/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/post/infrastructure/service/test.java
Labels: ⚒️Fix, ✨ Feature

#37 [Feature - March 1st, 2024]{POST, KEYWORD} 수정 완료
  src/main/java/com/runninghi/runninghibackv2/feedback/domain/service/FeedbackDomainService.java
  src/main/java/com/runninghi/runninghibackv2/keyword/infrastructure/service/KeywordCheckerImpl.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/aggregate/entity/Post.java
Labels: 🐞 BugFix

#53 [Feature - March 2nd, 2024]{KEYWORD} 키워드 테스트 코드 작성
  src/main/java/com/runninghi/runninghibackv2/keyword/application/dto/response/KeywordResponse.java
  src/main/java/com/runninghi/runninghibackv2/keyword/domain/service/KeywordChecker.java
  src/main/java/com/runninghi/runninghibackv2/keyword/infrastructure/service/KeywordCheckerImpl.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/aggregate/entity/Post.java
  src/test/java/com/runninghi/runninghibackv2/keyword/application/service/KeywordServiceTests.java
Labels: 🎯 Test

#59 [Feature - March 2nd, 2024]{POST, POSTKEYWORD} 게시글 CRUD 와 게시글_키워드 CRUD
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/application/dto/test.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/application/service/test.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/aggregate/entity/PostKeyword.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/domain/service/test.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/infrastructure/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/keyword/postkeyword/infrastructure/service/test.java
  src/main/java/com/runninghi/runninghibackv2/post/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/post/application/dto/request/CreatePostRequest.java
  src/main/java/com/runninghi/runninghibackv2/post/application/dto/request/UpdatePostRequest.java
  src/main/java/com/runninghi/runninghibackv2/post/application/dto/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/post/application/dto/response/UpdatePostResponse.java
  src/main/java/com/runninghi/runninghibackv2/post/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/aggregate/entity/Post.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/service/ApiPostService.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/service/CalculateGPX.java
  src/main/java/com/runninghi/runninghibackv2/post/infrastructure/service/ApiPostServiceImpl.java
  src/main/java/com/runninghi/runninghibackv2/post/infrastructure/service/test.java
  src/main/java/com/runninghi/runninghibackv2/post/postkeyword/application/dto/test.java
  src/main/java/com/runninghi/runninghibackv2/post/postkeyword/application/service/PostKeywordService.java
  src/main/java/com/runninghi/runninghibackv2/post/postkeyword/domain/aggregate/entity/PostKeyword.java
  src/main/java/com/runninghi/runninghibackv2/post/postkeyword/domain/aggregate/vo/PostKeywordId.java
  src/main/java/com/runninghi/runninghibackv2/post/postkeyword/domain/repository/PostKeywordRepository.java
  src/main/java/com/runninghi/runninghibackv2/post/postkeyword/domain/service/test.java
  src/main/java/com/runninghi/runninghibackv2/post/postkeyword/infrastructure/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/post/postkeyword/infrastructure/service/test.java
Labels: ✨ Feature

#62 [Feature - Mar 3rd, 2024] - {POSTREPORT} 게시글 신고 엔티티 수정 및 저장 기능 구현
  src/main/java/com/runninghi/runninghibackv2/common/enumtype/ProcessingStatus.java
  src/main/java/com/runninghi/runninghibackv2/common/enumtype/ReportCategory.java
  src/main/java/com/runninghi/runninghibackv2/postreport/application/controller/PostReportController.java
  src/main/java/com/runninghi/runninghibackv2/postreport/application/dto/request/CreatePostReportRequest.java
  src/main/java/com/runninghi/runninghibackv2/postreport/application/dto/response/CreatePostReportResponse.java
  src/main/java/com/runninghi/runninghibackv2/postreport/application/dto/test.java
  src/main/java/com/runninghi/runninghibackv2/postreport/application/service/PostReportService.java
  src/main/java/com/runninghi/runninghibackv2/postreport/domain/aggregate/entity/PostReport.java
  src/main/java/com/runninghi/runninghibackv2/postreport/domain/service/PostReportChecker.java
  src/main/java/com/runninghi/runninghibackv2/postreport/domain/service/test.java
Labels: 🔨 Refactor, ✨ Feature

#87 [Test- Mar 3rd, 2024]{POST, POSTKEYWORD} 게시글, 게시글_키워드 CRUD 테스트 코드 작성
  src/main/java/com/runninghi/runninghibackv2/keyword/application/controller/KeywordController.java
  src/main/java/com/runninghi/runninghibackv2/keyword/application/service/KeywordService.java
  src/main/java/com/runninghi/runninghibackv2/keyword/domain/repository/KeywordRepository.java
  src/main/java/com/runninghi/runninghibackv2/keyword/domain/service/KeywordChecker.java
  src/main/java/com/runninghi/runninghibackv2/post/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/post/application/dto/response/CreatePostResponse.java
  src/main/java/com/runninghi/runninghibackv2/post/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/service/PostChecker.java
  src/main/java/com/runninghi/runninghibackv2/post/postkeyword/application/service/PostKeywordService.java
  src/test/java/com/runninghi/runninghibackv2/keyword/application/service/KeywordServiceTests.java
  src/test/java/com/runninghi/runninghibackv2/post/application/service/PostServiceTests.java
Labels: 🎯 Test

#90 [Feature - Mar 3rd, 2024]{REPLY, BOOKMARK} 요청 인자 관리 방법 리팩토링
  src/main/java/com/runninghi/runninghibackv2/auth/jwt/JwtTokenProvider.java
  src/main/java/com/runninghi/runninghibackv2/bookmark/application/controller/BookmarkController.java
  src/main/java/com/runninghi/runninghibackv2/bookmark/application/dto/request/BookmarkMemberInfoRequest.java
  src/main/java/com/runninghi/runninghibackv2/bookmark/application/dto/request/CreateBookmarkRequest.java
  src/main/java/com/runninghi/runninghibackv2/bookmark/application/service/BookmarkService.java
  src/main/java/com/runninghi/runninghibackv2/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/dto/request/DeleteReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/dto/request/UpdateReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/service/ReplyService.java
  src/test/java/com/runninghi/runninghibackv2/reply/application/service/ReplyServiceTest.java
Labels: 🔨 Refactor

#93 [Feature - Mar 3rd, 2024]{BOOKMARK, REPLY} 테스트 코드 작성 및 명칭 변경
  src/main/java/com/runninghi/runninghibackv2/bookmark/application/controller/BookmarkController.java
  src/main/java/com/runninghi/runninghibackv2/bookmark/application/service/BookmarkService.java
  src/main/java/com/runninghi/runninghibackv2/bookmark/domain/aggregate/vo/BookmarkId.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/service/ReplyService.java
  src/test/java/com/runninghi/runninghibackv2/bookmark/application/service/BookmarkServiceTest.java
  src/test/java/com/runninghi/runninghibackv2/reply/application/service/ReplyServiceTest.java
Labels: 🎯 Test

#102 [Refactor - Mar 3rd, 2024]{BOOKMARK, REPLY} Requset 방식 변경
  src/main/java/com/runninghi/runninghibackv2/auth/jwt/JwtTokenProvider.java
  src/main/java/com/runninghi/runninghibackv2/bookmark/application/controller/BookmarkController.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/controller/ReplyController.java
Labels: 🔨 Refactor

#105 [Feature- Mar 3rd, 2024] {POST} Post 신고횟수 칼럼 추가
  src/main/java/com/runninghi/runninghibackv2/post/domain/aggregate/entity/Post.java
  src/test/java/com/runninghi/runninghibackv2/post/application/service/PostServiceTests.java
Labels: ✨ Feature

#109 [Feature - Mar 4th, 2024]{Member} 카카오 로그인 설정
  src/main/java/com/runninghi/runninghibackv2/auth/jwt/JwtTokenProvider.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/InvalidTokenException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/KakaoLoginException.java
  src/main/java/com/runninghi/runninghibackv2/common/filter/JwtTokenFilter.java
  src/main/java/com/runninghi/runninghibackv2/common/response/ErrorCode.java
  src/main/java/com/runninghi/runninghibackv2/config/WebConfig.java
  src/main/java/com/runninghi/runninghibackv2/member/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/member/application/dto/response/KakaoProfileResponse.java
  src/main/java/com/runninghi/runninghibackv2/member/application/dto/test.java
  src/main/java/com/runninghi/runninghibackv2/member/application/service/KakaoLoginService.java
  src/main/java/com/runninghi/runninghibackv2/member/domain/repository/MemberRefreshTokenRepository.java
  src/main/java/com/runninghi/runninghibackv2/member/domain/repository/MemberRepository.java
  src/test/java/com/runninghi/runninghibackv2/common/filter/JwtTokenFilterTests.java
Labels: 📃 Docs, ✨ Feature

#114 [Bugfix, Refactoring - Mar 4th, 2024]{ Member} 카카오 로그인 관련 오류 수정
  src/main/java/com/runninghi/runninghibackv2/auth/jwt/JwtTokenProvider.java
  src/main/java/com/runninghi/runninghibackv2/bookmark/application/controller/BookmarkController.java
  src/main/java/com/runninghi/runninghibackv2/common/dto/AccessTokenInfo.java
  src/main/java/com/runninghi/runninghibackv2/common/dto/RefreshTokenInfo.java
  src/main/java/com/runninghi/runninghibackv2/member/application/service/KakaoLoginService.java
  src/main/java/com/runninghi/runninghibackv2/member/domain/aggregate/entity/Member.java
  src/main/java/com/runninghi/runninghibackv2/member/domain/aggregate/entity/MemberRefreshToken.java
  src/main/java/com/runninghi/runninghibackv2/member/domain/repository/MemberRefreshTokenRepository.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/controller/ReplyController.java
  src/test/java/com/runninghi/runninghibackv2/auto/jwt/JwtTokenProviderTests.java
Labels: 🔨 Refactor, 🐞 BugFix

#115 [Feature - Mar 4th, 2024]{Feedback} 컨트롤러에서 token을 쓰도록 수정
  src/main/java/com/runninghi/runninghibackv2/feedback/application/controller/FeedbackController.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/service/FeedbackService.java
  src/main/java/com/runninghi/runninghibackv2/feedback/domain/aggregate/entity/Feedback.java
  src/test/java/com/runninghi/runninghibackv2/feedback/application/service/FeedbackServiceTests.java
Labels: 🔨 Refactor, ⚒️Fix

#121 [Feature - Mar 4th, 2024]{POST} 게시글 전체 조회, MemberService 멤버 조회 로직 추가
  src/main/java/com/runninghi/runninghibackv2/member/application/service/MemberService.java
  src/main/java/com/runninghi/runninghibackv2/post/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/post/application/dto/response/GetAllPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/post/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/repository/PostRepository.java
  src/main/java/com/runninghi/runninghibackv2/post/infrastructure/service/ApiPostServiceImpl.java
Labels: ✨ Feature

#126 [Test- Mar 4th, 2024]{POST} 게시글 Scroll 테스트 코드 작성
  src/main/java/com/runninghi/runninghibackv2/member/application/service/MemberService.java
  src/main/java/com/runninghi/runninghibackv2/post/application/service/PostService.java
  src/test/java/com/runninghi/runninghibackv2/post/application/service/PostServiceTests.java
Labels: 🎯 Test, ⚒️Fix

#127 [Feature - Mar 4th, 2024]{Feedback}{Filter} controller 테스트, filter 예외 처리 수정
  build.gradle
  src/main/java/com/runninghi/runninghibackv2/auth/jwt/JwtTokenProvider.java
  src/main/java/com/runninghi/runninghibackv2/common/filter/JwtTokenFilter.java
  src/main/java/com/runninghi/runninghibackv2/common/response/ErrorCode.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/controller/FeedbackController.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/service/FeedbackService.java
  src/main/java/com/runninghi/runninghibackv2/feedback/domain/service/FeedbackChecker.java
  src/test/java/com/runninghi/runninghibackv2/common/filter/JwtTokenFilterTests.java
  src/test/java/com/runninghi/runninghibackv2/feedback/application/controller/FeedbackControllerTest.java
  src/test/java/com/runninghi/runninghibackv2/feedback/application/service/FeedbackServiceTests.java
Labels: 🔨 Refactor, 🎯 Test
