Repository cca-ffodregamdi/RunningHi-Back, pull requests merged in 2024-04, with the labels that each got.

#131 [#130] feat : @RequestParam의 @Pattern 형식에 안맞을 때 예외 처리 추가
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
  src/main/java/com/runninghi/runninghibackv2/common/response/ErrorCode.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/controller/FeedbackController.java
Labels: ⚒️Fix

#144 [Feature - Apr 1st, 2024]{REPLY} Request Param을 DTO로 묶는 기능 구현
  src/main/generated/com/runninghi/runninghibackv2/replyreport/domain/aggregate/entity/QCommentReport.java
  src/main/java/com/runninghi/runninghibackv2/commentreport/application/dto/test.java
  src/main/java/com/runninghi/runninghibackv2/commentreport/domain/aggregate/vo/test.java
  src/main/java/com/runninghi/runninghibackv2/commentreport/domain/repository/CommentReportRepository.java
  src/main/java/com/runninghi/runninghibackv2/commentreport/domain/service/test.java
  src/main/java/com/runninghi/runninghibackv2/commentreport/infrastructure/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/commentreport/infrastructure/service/test.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/dto/request/GetReportedReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/dto/request/GetReportedReplySearchRequest.java
  src/main/java/com/runninghi/runninghibackv2/replyreport/application/dto/test.java
  src/main/java/com/runninghi/runninghibackv2/replyreport/application/service/ReplyReportService.java
  src/main/java/com/runninghi/runninghibackv2/replyreport/domain/aggregate/entity/CommentReport.java
  src/main/java/com/runninghi/runninghibackv2/replyreport/domain/aggregate/vo/test.java
  src/main/java/com/runninghi/runninghibackv2/replyreport/domain/repository/ReplyReportRepository.java
  src/main/java/com/runninghi/runninghibackv2/replyreport/domain/service/test.java
  src/main/java/com/runninghi/runninghibackv2/replyreport/infrastructure/repository/test.java
  src/main/java/com/runninghi/runninghibackv2/replyreport/infrastructure/service/test.java
Labels: 🔨 Refactor, ✨ Feature

#147 [Refacor - Apr 1st, 2024]{REPLY} 신고 처리 상태에 따른 필터링 기능 리팩토링
  src/main/generated/com/runninghi/runninghibackv2/reply/domain/aggregate/entity/QReply.java
  src/main/generated/com/runninghi/runninghibackv2/replyreport/domain/aggregate/entity/QCommentReport.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/reply/application/dto/request/GetReportedReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/reply/domain/aggregate/entity/Reply.java
  src/main/java/com/runninghi/runninghibackv2/reply/infrastructure/repository/ReplyQueryRepositoryImpl.java
Labels: 🔨 Refactor

#150 [Feature- Apr 1st, 2024]{POST} 게시글 작성, 삭제 시 작성자 확인
  src/main/generated/com/runninghi/runninghibackv2/postreport/domain/aggregate/entity/QPostReport.java
  src/main/java/com/runninghi/runninghibackv2/post/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/post/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/post/application/service/UpdateService.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/service/PostChecker.java
  src/main/java/com/runninghi/runninghibackv2/postreport/infrastructure/service/ApiPostReportServiceImpl.java
  src/test/java/com/runninghi/runninghibackv2/post/application/service/PostServiceTests.java
Labels: 🎯 Test, ✨ Feature

#153 [Feature- Apr 1st, 2024]{POST} 신고 게시글 조회 시 필터링
  src/main/java/com/runninghi/runninghibackv2/post/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/post/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/post/domain/repository/PostRepository.java
  src/test/java/com/runninghi/runninghibackv2/post/application/service/PostServiceTests.java
Labels: ✨ Feature

#154 [Feature - Feb 1st, 2024]{Member} 회원탈퇴, 회원 정보 조회, 컬럼 추가
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/KakaoLoginException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/KakaoOauthException.java
  src/main/java/com/runninghi/runninghibackv2/common/response/ErrorCode.java
  src/main/java/com/runninghi/runninghibackv2/member/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/member/application/dto/request/UpdateMemberInfoRequest.java
  src/main/java/com/runninghi/runninghibackv2/member/application/dto/response/GetMemberResponse.java
  src/main/java/com/runninghi/runninghibackv2/member/application/dto/response/UpdateMemberInfoResponse.java
  src/main/java/com/runninghi/runninghibackv2/member/application/service/KakaoOauthService.java
  src/main/java/com/runninghi/runninghibackv2/member/application/service/MemberService.java
  src/main/java/com/runninghi/runninghibackv2/member/domain/aggregate/entity/Member.java
  src/main/java/com/runninghi/runninghibackv2/member/domain/service/MemberChecker.java
Labels: ✨ Feature

#160 [Refactor- Apr 1st, 2024]{POST} 게시글 컨트롤러 리팩토링
  src/main/java/com/runninghi/runninghibackv2/post/application/controller/PostController.java
Labels: 🔨 Refactor

#170 [Feature - Apr 2nd, 2024]{Member} member 생성 시 기본값을 넣도록 수정
  src/main/generated/com/runninghi/runninghibackv2/member/domain/aggregate/entity/QMember.java
  src/main/java/com/runninghi/runninghibackv2/member/application/dto/response/GetMemberResponse.java
  src/main/java/com/runninghi/runninghibackv2/member/application/service/KakaoOauthService.java
  src/main/java/com/runninghi/runninghibackv2/member/domain/aggregate/entity/Member.java
Labels: 🐞 BugFix

#171 [Refactoring - Apr 2nd, 2024]{Common} ApiResult 제네릭으로 변경
  src/main/java/com/runninghi/runninghibackv2/common/response/ApiResult.java
  src/main/java/com/runninghi/runninghibackv2/config/SwaggerConfig.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/controller/FeedbackController.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/dto/request/CreateFeedbackRequest.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/dto/request/DeleteFeedbackRequest.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/dto/request/GetFeedbackRequest.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/dto/request/UpdateFeedbackReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/dto/request/UpdateFeedbackRequest.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/dto/response/CreateFeedbackResponse.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/dto/response/DeleteFeedbackResponse.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/dto/response/GetFeedbackResponse.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/dto/response/UpdateFeedbackReplyResponse.java
  src/main/java/com/runninghi/runninghibackv2/feedback/application/dto/response/UpdateFeedbackResponse.java
Labels: 🔨 Refactor, ✨ Feature

#175 [Feature - Apr 2nd, 2024]{Member} Swagger 설정
  src/main/java/com/runninghi/runninghibackv2/member/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/member/application/dto/response/GetMemberResponse.java
  src/main/java/com/runninghi/runninghibackv2/member/application/dto/response/UpdateMemberInfoResponse.java
Labels: ✨ Feature

#188 [ BugFix - Apr 3rd, 2024]{COMMON} FCM 파일 복사 태스크 생성
  build.gradle
Labels: 🐞 BugFix

#190 [Feature - Apr 3rd, 2024]{Member, Feedback} Builder 어노테이션으로 수정
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Feedback.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Member.java
  src/test/java/com/runninghi/runninghibackv2/application/service/PostServiceTests.java
Labels: 🔨 Refactor

#192 [Feature - Apr 3rd, 2024]{REPLY, BOOKMARK} Swagger 설정
  .gitignore
  src/main/java/com/runninghi/runninghibackv2/application/controller/BookmarkController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/alarm/ReplyFCMDTO.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/bookmark/request/BookmarkMemberInfoRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/bookmark/request/CreateBookmarkRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/bookmark/response/CreateBookmarkResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/notification/request/FCMNotificationRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/CreateReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/DeleteReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/GetReportedReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/GetReportedReplySearchRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/UpdateReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/CreateReplyResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetReplyListResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/UpdateReplyResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ReplyService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/vo/BookmarkId.java
Labels: ✨ Feature

#196 [Refactor- Apr 3rd, 2024]{POST, KEYWORD} POST-KEYWORD 양방향 연관관계 설정
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/CreateRecordRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/PostKeywordRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Keyword.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Post.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/PostKeyword.java
Labels: 🔨 Refactor, ✨ Feature

#198 [Feature - Apr 3rd, 2024]{POST} 게시글 전체 조회 시 키워드 별 필터링 적용
  src/main/generated/com/runninghi/runninghibackv2/domain/entity/QPost.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/PostKeywordCriteria.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetAllPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/test/java/com/runninghi/runninghibackv2/application/service/FeedbackServiceTests.java
  src/test/java/com/runninghi/runninghibackv2/application/service/KeywordServiceTests.java
  src/test/java/com/runninghi/runninghibackv2/application/service/PostServiceTests.java
Labels: ✨ Feature

#204 [Feature - Apr 4th, 2024]{IMAGE} 이미지 API 기능 구현
  build.gradle
  src/main/java/com/runninghi/runninghibackv2/application/controller/ImageController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/image/response/CreateImageResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/image/response/DownloadImageResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/CreatePostRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/PostImageRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ImageService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/auth/jwt/JwtTokenProvider.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
  src/main/java/com/runninghi/runninghibackv2/config/AWSS3Config.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Image.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ImageRepository.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/ImageChecker.java
  src/test/java/com/runninghi/runninghibackv2/application/model/ImageTestModel.java
  src/test/java/com/runninghi/runninghibackv2/application/service/PostServiceTests.java
  src/test/java/com/runninghi/runninghibackv2/domain/service/ImageCheckerTest.java
Labels: 🐞 BugFix, ✨ Feature
