Repository cca-ffodregamdi/RunningHi-Back, pull requests merged in 2024-08, with the labels that each got.

#477 [#474] Refactor : 2024-08-04 더미데이터 xml 파일 분리
  src/main/resources/mapper/AlarmDummy.xml
  src/main/resources/mapper/BookmarkDummy.xml
  src/main/resources/mapper/ChallengDummy.xml
  src/main/resources/mapper/ImageDummy.xml
  src/main/resources/mapper/LikeDummy.xml
  src/main/resources/mapper/MemberDummy.xml
  src/main/resources/mapper/PostDummy.xml
  src/main/resources/mapper/RecordDummy.xml
  src/main/resources/mapper/ReplyDummy.xml
  src/main/resources/mapper/ReportDummy.xml
  src/main/resources/mapper/ResetDatabase.xml
Labels: 🔨 Refactor

#476 [#473] Refactor : 2024-08-04 챌린지 더미데이터에 이미지 추가
  src/main/resources/data/challenges.sql
Labels: 🔨 Refactor

#478 [#467] Feat : 사용자의 위치 정보 저장 api
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/request/UpdateCurrentLocationRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/UpdateCurrentLocationResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/MemberService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Member.java
Labels: ✨ Feature

#481 [#480] Refactor : 2024-08-05 Alarm 더미데이터 추가
  src/main/resources/data/alarms.sql
  src/main/resources/mapper/AlarmDummy.xml
Labels: 🔨 Refactor

#482 [#451] Feature - 알림 읽음 처리 구현
  src/main/java/com/runninghi/runninghibackv2/application/controller/AlarmController.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Alarm.java
  src/main/java/com/runninghi/runninghibackv2/domain/enumtype/AlarmType.java
Labels: ✨ Feature

#488 [#485] Feature : 러닝 GPS 저장 & 기록 조회 API 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/RunDataRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetRecordPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GpsDataResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/GetMonthlyRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/GetWeeklyRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/GetYearlyRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/RecordData.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Post.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/vo/GpsDataVO.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/RecordQueryRepositoryImpl.java
  src/main/resources/data/posts.sql
  src/main/resources/mapper/PostDummy.xml
  src/test/java/com/runninghi/runninghibackv2/application/service/BookmarkServiceTest.java
  src/test/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatchTests.java
Labels: ⚒️Fix, ✨ Feature

#490 [#489] 챌린지 더미데이터, 전체조회 API 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/ChallengeController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/ChallengeListResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/GetAllChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/GetAllMyChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/MyChallengeListResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ChallengeService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/MyChallengeService.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ChallengeRepository.java
  src/main/resources/data/MemberChallenges.sql
  src/main/resources/data/challenges.sql
  src/main/resources/mapper/ChallengDummy.xml
Labels: 🔨 Refactor

#492 [#491] Feature : 게시글 상세조회 API 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: ⚒️Fix, ✨ Feature

#494 [Dummy] - 이미지 추가
  src/main/resources/data/images.sql
  src/main/resources/data/posts.sql
  src/main/resources/mapper/ImageDummy.xml
  src/main/resources/mapper/PostDummy.xml
Labels: ⚒️Fix

#496 [#459] [Feature] POST 도메인 로깅 설정
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/S3UploadException.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/PostChecker.java
Labels: ✨ Feature

#497 [#493] Bugfix - 스케줄링 테스트 오류 수정
  src/main/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatch.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Alarm.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ReplyReportRepository.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ReplyRepository.java
  src/test/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatchTests.java
Labels: 🐞 BugFix

#499 [#498] refactor : 피드백 관리자 전체 조회에 필터링(reply) 추가
  src/main/java/com/runninghi/runninghibackv2/application/controller/FeedbackController.java
  src/main/java/com/runninghi/runninghibackv2/application/service/FeedbackService.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/FeedbackRepository.java
Labels: 🔨 Refactor

#501 [#500] refactor : 테스트 코드에 @Transactional 어노테이션 추가
  src/test/java/com/runninghi/runninghibackv2/application/service/FaqServiceTests.java
  src/test/java/com/runninghi/runninghibackv2/auth/jwt/JwtTokenProviderTests.java
  src/test/java/com/runninghi/runninghibackv2/common/filter/JwtTokenFilterTests.java
  src/test/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatchTests.java
Labels: 🔨 Refactor, 🐞 BugFix

#506 [#505] 더미 데이터 수정
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/resources/data/MemberChallenges.sql
  src/main/resources/data/alarms.sql
  src/main/resources/data/bookmarks.sql
  src/main/resources/data/challenges.sql
  src/main/resources/data/like.sql
  src/main/resources/data/members.sql
  src/main/resources/data/postreports.sql
  src/main/resources/data/posts.sql
  src/main/resources/data/records.sql
  src/main/resources/data/replies.sql
  src/test/java/com/runninghi/runninghibackv2/application/service/FaqServiceTests.java
  src/test/java/com/runninghi/runninghibackv2/application/service/KeywordServiceTests.java
Labels: ✨ Feature

#511 Feature : 약관동의 여부 조회 & 약관동의 업데이트 기능 추가, 약관동의 컬럼 추가
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/GetIsTermsAgreedResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/TermsAgreementResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AppleOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/KakaoOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/MemberService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Member.java
Labels: ✨ Feature

#516 [#515] 지역설정 여부 API 추가
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/GetIsLocationResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AppleOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/KakaoOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/MemberService.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestToken.java
  src/main/resources/data/members.sql
  src/test/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatchTests.java
Labels: ✨ Feature

#518 [#517] 러닝데이터 저장 기록 적용 오류 수정
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/RecordService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Record.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/RecordRepository.java
Labels: 🐞 BugFix

#523 [#519] 게시글 조회 거리 필터 제거
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/PostQueryRepository.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: 🔨 Refactor, ⚒️Fix

#526 [#525] 게시글 중복조회 오류 수정
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: 🐞 BugFix

#527 [#524] 이미지 업로드 Utils 생성 & 이미지 Entity/Service 모듈화
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostImageController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/image/response/CreateImageResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/image/response/ImageTarget.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ImageService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ImageServiceImpl.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostImageService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostReportService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/common/utils/S3StorageUtils.java
  src/main/java/com/runninghi/runninghibackv2/common/utils/SecureStringUtils.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Image.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ImageRepository.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
  src/test/java/com/runninghi/runninghibackv2/application/service/ImageServiceImplTest.java
  src/test/java/com/runninghi/runninghibackv2/utils/S3StorageUtilsTest.java
Labels: 🔨 Refactor, 🎯 Test

#531 [#530] 이미지 업로드 Bugfix
  src/main/java/com/runninghi/runninghibackv2/common/utils/S3StorageUtils.java
  src/test/java/com/runninghi/runninghibackv2/utils/S3StorageUtilsTest.java
Labels: 🐞 BugFix

#532 [#522] 기본 프로필 이미지 설정 & 프로필 이미지 수정 추가
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/DeleteProfileImageResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/GetMemberResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/UpdateProfileImageResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/GetChallengeRankingResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetAllPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetMyPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetReportedPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/GetReplyList.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/UpdateReplyResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AppleOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ImageService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/KakaoOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/MemberService.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/ImageException.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Member.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/MemberChallengeRepository.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/MemberChecker.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/ReplyQueryRepositoryImpl.java
  src/test/java/com/runninghi/runninghibackv2/application/controller/FeedbackControllerTest.java
Labels: 🔨 Refactor, ✨ Feature

#539 [#538] BubFix : profileNickname을 nickname으로 변경, memberNo를 응답값에 추가
  src/main/java/com/runninghi/runninghibackv2/application/service/KakaoOauthService.java
  src/test/java/com/runninghi/runninghibackv2/application/controller/FeedbackControllerTest.java
Labels: 🐞 BugFix

#545 [#544] SSE 알림 기능 구현
  src/main/java/com/runninghi/runninghibackv2/application/controller/AlarmController.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
Labels: ✨ Feature
