Repository cca-ffodregamdi/RunningHi-Back, pull requests merged in 2024-07, with the labels that each got.

#390 Fix : 2024-06-26 게시글 상세보기 Response 수정
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
Labels: ⚒️Fix

#392 [#374] hotfix : 애플 회원탈퇴 오류 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AppleOauthService.java
  src/main/java/com/runninghi/runninghibackv2/auth/apple/AppleClient.java
Labels: 🐞 BugFix

#394 [#393] Feature: 기록페이지를 위한 Record 엔티티 생성
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Record.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/vo/RunDataVO.java
Labels: ✨ Feature

#397 [#395] Bugfix: POST 페이징, 중복 오류 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: 🐞 BugFix

#400 Refactor/#399 좋아요 API 응답 리팩토링
  src/main/java/com/runninghi/runninghibackv2/application/controller/LikeController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/like/response/CreateLikeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/like/response/LikeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetAllPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/LikeService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestDatabaseMapper.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/LikeRepository.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
  src/main/resources/data/like.sql
  src/main/resources/mapper/ResetDatabase.xml
Labels: 🔨 Refactor

#404 [#403] Refactor : 2024-07-03 서버 로깅 ci 설정
  .github/workflows/push-deploy-gradle.yml
Labels: 🏻‍🎤 Ci

#406 [#405] Feature: 24-07-04 좋아요, 북마크 게시글 조회
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetMyPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/PostQueryRepository.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: ✨ Feature

#409 [#408] refactor - 챌린지 목표 컬럼 명칭 변경
  src/main/java/com/runninghi/runninghibackv2/application/controller/ChallengeController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/request/CreateChallengeRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/request/UpdateChallengeRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/CreateChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/GetAllChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/GetChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/UpdateChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/GetMyChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ChallengeService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Challenge.java
Labels: 🔨 Refactor

#413 Feature - 게시글 관련 API 응답 시에 요청자 본인이 좋아요한 게시글인지 확인 여부 추가
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetAllPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetMyPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ReplyService.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: ✨ Feature

#414 [#370] Feature - 기록 페이지 조회 시 주간/월간/연간 데이터 확인
  src/main/java/com/runninghi/runninghibackv2/application/controller/RecordController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetRecordPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/GetMonthlyRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/GetWeeklyRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/GetYearlyRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/RecordService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Record.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/PostQueryRepository.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/RecordQueryRepository.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/RecordQueryRepositoryImpl.java
  src/main/resources/data/records.sql
Labels: ✨ Feature

#421 [#419] BugFix: 애플 로그인 client-id mismatch 오류 수정
  src/main/java/com/runninghi/runninghibackv2/auth/apple/AppleClaimsValidator.java
Labels: 🐞 BugFix

#424 [#423] Refactoring - 챌린지 컬럼 변경, 챌린지 전체조회, 상세조회 API 변경
  src/main/java/com/runninghi/runninghibackv2/application/controller/ChallengeController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/request/CreateChallengeRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/request/UpdateChallengeRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/ChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/CreateChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/GetChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/challenge/response/UpdateChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/GetAllMyChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/memberchallenge/response/GetMyChallengeResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ChallengeService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Challenge.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/MemberChallenge.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ChallengeQueryRepository.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/ChallengeQueryRepositoryImpl.java
  src/main/resources/mapper/ResetDatabase.xml
Labels: 🔨 Refactor, ✨ Feature

#426 [#425] Feature - 게시글 상세조회 시 좋아요 여부 포함
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: ✨ Feature

#428 [#427] Hotfix - 난이도 명칭 수정
  src/main/java/com/runninghi/runninghibackv2/domain/enumtype/Difficulty.java
Labels: ⚒️Fix

#430 [#429] Hotfix - 상세보기 좋아요 개수 오류 수정
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: 🐞 BugFix

#437 [#436] bugfix : identityToken -> identityCode로 변수명 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/request/AppleLoginRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AppleOauthService.java
Labels: 🐞 BugFix

#440 Dummy - 게시글 더미데이터 멤버 수정
  src/main/resources/data/posts.sql
Labels: ✨ Feature

#444 [#443] refactor : identityCode-> identityToken으로 변수명 변경
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/request/AppleLoginRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AppleOauthService.java
Labels: 🔨 Refactor

#447 [#422] Feature: 러닝기록 저장 로직 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/BookmarkController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/bookmark/response/BookmarkedPostListResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/RunDataRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/CreateRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetRecordPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/common/converter/IntegerListConverter.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Post.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/vo/GpsDataVO.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/GpsCalculator.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
  src/main/resources/data/posts.sql
  src/main/resources/mapper/ResetDatabase.xml
  src/test/java/com/runninghi/runninghibackv2/application/service/BookmarkServiceTest.java
  src/test/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatchTests.java
Labels: ✨ Feature

#448 [#402] Feature - 알림 리스트, 생성 API 구현
  src/main/java/com/runninghi/runninghibackv2/application/controller/AlarmController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/alarm/request/CreateAlarmRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/alarm/response/GetAllAlarmResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
  src/main/java/com/runninghi/runninghibackv2/common/response/ErrorCode.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Alarm.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/AlarmRepository.java
Labels: ✨ Feature

#452 [#449] feat : 레벨업에 필요한 거리 수정
  src/main/java/com/runninghi/runninghibackv2/domain/entity/vo/RunDataVO.java
Labels: ✨ Feature

#453 [#451] Refactor - 알림리스트 조회 시 미확인 알림만 조회, 특정 회원의 알림 생성
  src/main/java/com/runninghi/runninghibackv2/application/controller/AlarmController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/alarm/request/CreateAlarmRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
Labels: 🔨 Refactor

#458 [#456] Fix- 러닝 기록 오류 수정
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetRecordPostResponse.java
  src/main/resources/data/records.sql
Labels: ⚒️Fix

#461 [#460] Feature - 코스 기록 txt 파일로 저장하도록 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Post.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/GpsCalculator.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/GpsCoordinateExtractor.java
Labels: ⚒️Fix, ✨ Feature

#462 Hotfix: 24-07-26 GPS ResetDatabase 오류 수정
  src/main/resources/mapper/ResetDatabase.xml
Labels: 🐞 BugFix

#465 [#450] Feature - member 도메인 로깅
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AppleOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/KakaoOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/MemberService.java
Labels: ✨ Feature
