Repository cca-ffodregamdi/RunningHi-Back, pull requests merged in 2024-05, with the labels that each got.

#211 [Docs -May 1st, 2024]{Feedback}{Member} Swagger, 문서화 주석 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/FeedbackController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
Labels: 🗨️ Comment, 📃 Docs

#214 [Feature - May 1st, 2024] - {Feedback} 피드백 조회 시 피드백 번호 누락 수정
  src/main/java/com/runninghi/runninghibackv2/application/dto/feedback/response/GetFeedbackResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/feedback/response/UpdateFeedbackReplyResponse.java
  src/test/java/com/runninghi/runninghibackv2/application/controller/FeedbackControllerTest.java
Labels: 🔨 Refactor, ✨ Feature

#217 [Feature - May 1st, 2024] - {POST} Swagger-UI API 문서 작성 & GPX S3 연동
  src/main/generated/com/runninghi/runninghibackv2/domain/entity/QPost.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/CreatePostRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/PostKeywordCriteria.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/UpdatePostRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/CreatePostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/CreateRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/DeletePostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GpxDataResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/config/AWSS3Config.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Post.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/GpxCalculator.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/GpxCoordinateExtractor.java
  src/main/resources/suwon.gpx
  src/main/resources/test.gpx
  src/test/java/com/runninghi/runninghibackv2/application/service/PostServiceTests.java
Labels: 📃 Docs, ✨ Feature

#222 [Docs - May 2nd, 2024]{Bookmark, Image, Reply} Api Result 수정, swagger 상세 설정
  src/main/java/com/runninghi/runninghibackv2/application/controller/BookmarkController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/ImageController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/CreateReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetReplyListResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ReplyService.java
Labels: 🔨 Refactor, 🗨️ Comment, 📃 Docs

#219 [Docs - May 1st, 2024]{PostReport, ReplyReport} 신고 도메인 Swagger 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostReportController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/ReplyReportController.java
Labels: 📃 Docs

#227 [Style - May 2nd, 2024] - {Feedback}{Member} 컨트롤러에 produces 속성 추가
  src/main/java/com/runninghi/runninghibackv2/application/controller/FeedbackController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
Labels: ⚒️Fix

#230 [Feature- May 2nd, 2024] - {Post} 컨트롤러에 produces 속성 추가
  build.gradle
  src/main/generated/com/runninghi/runninghibackv2/domain/entity/vo/QGpxDataVO.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/bookmark/response/BookmarkedPostListResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/vo/GpxDataVO.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/GpxCalculator.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/GpxCoordinateExtractor.java
  src/test/java/com/runninghi/runninghibackv2/application/service/BookmarkServiceTest.java
  src/test/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatchTests.java
Labels: 🔨 Refactor, ✨ Feature

#233 [ BugFix, Refactor - May 3rd, 2024]{Bookmar, Reply, Image} API 점검 및 오류 수정
  src/main/generated/com/runninghi/runninghibackv2/domain/entity/QReply.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/ImageController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/ReplyController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/CreateReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/GetReportedReplyRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/request/GetReportedReplySearchRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetReplyListResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/reply/response/GetReportedReplyResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ReplyService.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
  src/main/java/com/runninghi/runninghibackv2/common/response/ApiResult.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Reply.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ReplyQueryRepository.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/ReplyChecker.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/ReplyQueryRepositoryImpl.java
  src/test/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatchTests.java
  src/test/java/com/runninghi/runninghibackv2/domain/service/ReplyCheckerTest.java
Labels: 🔨 Refactor, 🐞 BugFix

#239 [BugFix - May 3rd, 2024]{Post} 게시글 전체 조회 시 이미지 url 조회
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetAllPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
Labels: 🐞 BugFix

#244 [BugFix - May 3rd, 2024]{Post} GPS 데이터 저장 시 거리/시간 누적 계산 버그
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/GpsCalculator.java
Labels: 🐞 BugFix

#246 [Feature - May 3rd, 2024] - {Member} 토큰 유효성 체크 API
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/auth/jwt/JwtTokenProvider.java
  src/main/java/com/runninghi/runninghibackv2/common/filter/JwtTokenFilter.java
  src/main/java/com/runninghi/runninghibackv2/common/response/ApiResult.java
Labels: 🔨 Refactor, ✨ Feature

#250 [Refactoring - May 4th, 2024] - {Feedback} feedback 작성시 enum 타입을 받는 것으로 수정
  src/main/java/com/runninghi/runninghibackv2/application/dto/feedback/request/CreateFeedbackRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/feedback/request/UpdateFeedbackRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/service/FeedbackService.java
  src/test/java/com/runninghi/runninghibackv2/application/controller/FeedbackControllerTest.java
  src/test/java/com/runninghi/runninghibackv2/application/service/FeedbackServiceTests.java
Labels: 🔨 Refactor

#247 [Feature - May 3rd, 2024] - {POST} 게시글 엔티티&응답 추가/삭제, 마이피드 전체조회
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/bookmark/response/BookmarkedPostListResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/CreatePostRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/UpdatePostRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetAllPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GpsDataResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/UpdatePostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostKeywordService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Post.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/vo/GpsDataVO.java
  src/main/java/com/runninghi/runninghibackv2/domain/enumtype/Difficulty.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/GpsCalculator.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/GpxCoordinateExtractor.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/PostChecker.java
  src/test/java/com/runninghi/runninghibackv2/application/service/BookmarkServiceTest.java
  src/test/java/com/runninghi/runninghibackv2/application/service/ReplyServiceTest.java
  src/test/java/com/runninghi/runninghibackv2/common/schedule/MemberCleanupBatchTests.java
Labels: ⚒️Fix, ✨ Feature

#253 [BugFix - May 4th, 2024] - {Dummy} 테스트 토큰 발급 & 테스트 데이터 API 오류 수정
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestData.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestToken.java
  src/main/java/com/runninghi/runninghibackv2/common/filter/JwtTokenFilter.java
Labels: 🐞 BugFix

#257 [Test- May 4th, 2024] - {Dummy} 테스트용 기록 insert SQL
  src/main/resources/data/posts.sql
Labels: 🎯 Test

#260 [Bugfix- May 4th, 2024] - {Post} 게시글 전체 조회 페이징 오류 해결
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/request/PostKeywordCriteria.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
Labels: 🐞 BugFix
