Repository cca-ffodregamdi/RunningHi-Back, pull requests merged in 2024-09, with the labels that each got.

#549 [#543] 도메인별 알림 트리거 설정
  src/main/java/com/runninghi/runninghibackv2/application/controller/AlarmController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/BookmarkController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/FeedbackController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/LikeController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/PostImageController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/RecordController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/ReplyReportController.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AppleOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ChallengeService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/FeedbackService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/KakaoOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/LikeService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostImageService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostReportService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ReplyService.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/FcmException.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Alarm.java
  src/main/java/com/runninghi/runninghibackv2/domain/enumtype/AlarmType.java
Labels: ✨ Feature

#554 [#544] 이미지가
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
Labels: 🐞 BugFix

#555 [#552] 이미지 업로드 간 예외 처리 추가 및 용량 증가
  src/main/java/com/runninghi/runninghibackv2/application/service/ImageServiceImpl.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/CustomEntityNotFoundException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/ImageException.java
  src/main/java/com/runninghi/runninghibackv2/common/utils/S3StorageUtils.java
  src/main/java/com/runninghi/runninghibackv2/common/utils/SecureStringUtils.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/ImageChecker.java
  src/test/java/com/runninghi/runninghibackv2/application/service/ImageServiceImplTest.java
  src/test/java/com/runninghi/runninghibackv2/domain/service/ImageCheckerTest.java
Labels: 🐞 BugFix

#557 [#556] RunDataVO 다음 거리까지 남은 거리 계산 수정
  src/main/java/com/runninghi/runninghibackv2/application/dto/member/response/GetMemberResponse.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/vo/RunDataVO.java
Labels: 🐞 BugFix

#562 [#560] 게시글 전체보기 Response isWriter 추가
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetAllPostsResponse.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: ⚒️Fix

#565 [#564] 앱스토어 심사용 버전확인 & 테스터 토큰 발급
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestReviewerResponse.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestToken.java
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestTokenResponse.java
Labels: ✨ Feature

#569 [#568] MainData 소수점 저장 형식 수정
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
Labels: ⚒️Fix

#571 [#570] 심사용 버전 형식 1.X.X 적용
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestToken.java
Labels: ⚒️Fix

#573 [#572] 거리(km) 저장 시 소수점 반올림
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
Labels: ⚒️Fix

#577 [#574][Refactor] 게시글 수정에 이미지 빈 값에 대한 요청 처리
  src/main/java/com/runninghi/runninghibackv2/application/service/ImageService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/ImageServiceImpl.java
  src/main/java/com/runninghi/runninghibackv2/application/service/MemberService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ImageRepository.java
Labels: 🔨 Refactor

#580 [#579] POST 삭제 시 해당하는 RECORD 삭제
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/RecordService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Record.java
  src/main/java/com/runninghi/runninghibackv2/domain/repository/RecordRepository.java
Labels: 🐞 BugFix

#582 [#581] GetWeeklyRecordResponse 명칭 수정
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/GetWeeklyRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/RecordService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Record.java
Labels: 🐞 BugFix

#585 [#584] POST 에 MainDataType 추가
  src/main/java/com/runninghi/runninghibackv2/application/dto/post/response/GetPostResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Post.java
Labels: ✨ Feature

#586 [#583] 러닝횟수 누락 수정
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/GetMonthlyRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/GetWeeklyRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/record/response/GetYearlyRecordResponse.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/RecordQueryRepositoryImpl.java
Labels: 🐞 BugFix

#590 [Refactor] 토큰 인증 메서드 제외
  src/main/java/com/runninghi/runninghibackv2/application/controller/MemberController.java
  src/main/java/com/runninghi/runninghibackv2/common/filter/JwtTokenFilter.java
Labels: 🐞 BugFix

#594 [#593][Bugfix] 프로필 업데이트 오류 수정
  src/main/java/com/runninghi/runninghibackv2/application/service/MemberService.java
Labels: 🐞 BugFix

#597 [#596][bugfix] currentVersion 값 변경
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestToken.java
Labels: 🐞 BugFix

#601 [#600] POST 수정 시 메인데이터 타입 (int) 수정 적용
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/main/java/com/runninghi/runninghibackv2/domain/entity/Post.java
Labels: 🐞 BugFix

#603 [#602] 이미지 수정 시에 기존 이미지, 새로운 이미지 여부에 따른 경우의 수를 나누어 로직 수정
  src/main/java/com/runninghi/runninghibackv2/application/service/ImageServiceImpl.java
  src/main/java/com/runninghi/runninghibackv2/domain/service/ImageChecker.java
Labels: 🐞 BugFix

#604 [#599] refactor : CustomException으로 수정, log 수정
  src/main/java/com/runninghi/runninghibackv2/application/controller/BookmarkController.java
  src/main/java/com/runninghi/runninghibackv2/application/controller/LikeController.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AppleOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/FaqService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/FeedbackService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/KakaoOauthService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/MemberService.java
  src/main/java/com/runninghi/runninghibackv2/application/service/NoticeService.java
  src/main/java/com/runninghi/runninghibackv2/auth/apple/ApplePublicKeyGenerator.java
  src/main/java/com/runninghi/runninghibackv2/auth/apple/ApplePublicKeys.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/GlobalExceptionHandler.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/AdminAccountDuplicatedException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/AdminInvalidInvitationCodeException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/AdminInvalidPasswordException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/AdminLoginException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/AdminUnauthorizedException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/AppleOauthClaimsException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/AppleOauthClientSecretException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/AppleOauthTokenException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/AppleOauthUnlinkException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/ApplePublicKeyGenerationException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/ApplePublicKeyNotFoundException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/FeedbackInvalidDataException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/ImageException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/KakaoOauthProfileException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/KakaoOauthUnlinkException.java
  src/main/java/com/runninghi/runninghibackv2/common/exception/custom/MemberInvalidDataException.java
  src/main/java/com/runninghi/runninghibackv2/common/response/ApiResult.java
  src/main/java/com/runninghi/runninghibackv2/common/response/ErrorCode.java
  src/test/java/com/runninghi/runninghibackv2/application/controller/FeedbackControllerTest.java
Labels: 🔨 Refactor

#607 [#598] Post Service 테스트 코드 작성
  src/main/java/com/runninghi/runninghibackv2/application/service/PostService.java
  src/test/java/com/runninghi/runninghibackv2/MotherObject/MemberMother.java
  src/test/java/com/runninghi/runninghibackv2/MotherObject/PostMother.java
  src/test/java/com/runninghi/runninghibackv2/application/service/PostServiceTests.java
Labels: 🎯 Test

#610 [Feature] 나의 게시글 조회 시 공유된 게시글만 조회되도록 수정
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
  src/test/java/com/runninghi/runninghibackv2/application/service/PostServiceTests.java
Labels: ✨ Feature

#612 [#611] FCM 푸쉬 알림 활성화
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
Labels: 🔨 Refactor

#614 [#613] 게시글 조회 시 삭제된 댓글 제외하고 조회
  src/main/java/com/runninghi/runninghibackv2/domain/repository/ReplyQueryRepository.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/ReplyQueryRepositoryImpl.java
Labels: 🐞 BugFix

#615 [#591][BugFix] 삭제된 댓글 리스트 제외 구현
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: 🐞 BugFix

#617 [#616] 푸쉬 알림 테스트 api 개설
  src/main/java/com/runninghi/runninghibackv2/application/controller/AlarmController.java
  src/main/java/com/runninghi/runninghibackv2/application/dto/alarm/request/CreateAlarmRequest.java
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
  src/main/java/com/runninghi/runninghibackv2/common/response/ApiResult.java
Labels: 🔨 Refactor
