Repository cca-ffodregamdi/RunningHi-Back, pull requests merged in 2024-10, with the labels that each got.

#623 [BugFix] 도커파일 워크 디렉토리 픽스
  Dockerfile-dev
  Dockerfile-prod
Labels: 🐞 BugFix

#624 [BugFix] 도커파일 워크 디렉토리 픽스
  Dockerfile-dev
  Dockerfile-prod
Labels: 🐞 BugFix

#626 2차 배포
  Dockerfile-dev
  Dockerfile-prod
Labels: 📃 Docs

#628 3차 시도!
  .github/workflows/push-deploy-dev.yml
Labels: 🐞 BugFix

#622 [#608] 기록탭 게시글 조회 누락 문제 해결
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: 🐞 BugFix

#629 [#608] Deploy
  src/main/java/com/runninghi/runninghibackv2/infrastructure/repository/PostQueryRepositoryImpl.java
Labels: 🌏 Deploy

#633 [#631][BugFix] 알림 서비스 안됨이슈
  .github/workflows/push-deploy-dev.yml
  .github/workflows/push-deploy-prod.yml
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
Labels: 🐞 BugFix

#636 [#635][Refactor] 현재 버전 1.0.3으로 업데이트(임시)
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestToken.java
Labels: 🔨 Refactor

#638 [#637] 푸쉬 알림 테스트를 위한 임시 업데이트
  .github/ISSUE_TEMPLATE/issue---🌏-deploy-md.md
  src/main/java/com/runninghi/runninghibackv2/common/dummy/TestToken.java
Labels: 🌏 Deploy

#639 [#634] 푸쉬 알림 서비스 버그 수정
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
Labels: 🐞 BugFix

#643 [#642][HotFix] 푸쉬 알림 서비스 임시 주석
  src/main/java/com/runninghi/runninghibackv2/application/service/AlarmService.java
Labels: 🌏 Deploy, 🐞 BugFix
